name: "Docker image build and upload"
description: "Docker image build and upload"

runs:
  using: "composite"
  inputs:
    working-directory:
      description: 'Working directory'
      required: false
      default: ''
  steps:
    - uses: ./.github/actions/docker-utils-before-script
    # - run: echo ${DOCKER_REGISTRY_PASS} | log docker login -u ${DOCKER_REGISTRY_USER} --password-stdin ${DOCKER_REGISTRY}
    - run: cd ${{ inputs.working-directory }} && docker build -t ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_FILE }}
      shell: bash
    - run: docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE_TAG }}
      shell: bash
    #- run: docker push ${DOCKER_IMAGE}
    #- run: docker push ${DOCKER_IMAGE_TAG}
