name: "Docker image build and upload"
description: "Docker image build and upload"
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: ''
  user:
    description: 'Username'
    required: true
    default: ''
  pass:
    description: 'Password'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/docker-utils-before-script
    - run: echo ${{ inputs.pass }} | log docker login -u ${{ inputs.user }} --password-stdin ${{ vars.DOCKER_REGISTRY }}
      shell: bash
    - run: cd ${{ inputs.working-directory }} && docker build -t ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_FILE }}
      shell: bash
    - run: docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE_TAG }}
      shell: bash
    # - run: docker push ${{ env.DOCKER_IMAGE }}
    #   shell: bash
    # - run: docker push ${{ env.DOCKER_IMAGE_TAG }}
    #   shell: bash
