name: "Docker image build and upload"
description: "Docker image build and upload"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/docker-utils-before-script
    # - run: echo ${DOCKER_REGISTRY_PASS} | log docker login -u ${DOCKER_REGISTRY_USER} --password-stdin ${DOCKER_REGISTRY}
    - run: docker build -t ${DOCKER_IMAGE} ${DOCKER_FILE}
      shell: bash
    - run: docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAG}
      shell: bash
    #- run: docker push ${DOCKER_IMAGE}
    #- run: docker push ${DOCKER_IMAGE_TAG}
