name: CI
on:
  push:
    branches:
      - "master"

env:
  DOCKER_REGISTRY_PATH: kit
  DOCKER_REGISTRY: registry.digitalocean.com

jobs:
  build_api:
    defaults:
      run:
        shell: bash
        working-directory: apps/api
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.0
      - uses: ./.github/actions/utils-before
      - run: pnpm install
      - run: pnpm build
      - run: pnpm -F "." deploy .release
      - uses: actions/upload-artifact@master
        with:
          name: api
          path: |
            ./apps/api/.release
            ./apps/api/lib
    
  docker_api:
    defaults:
      run:
        shell: bash
        working-directory: apps/api
    runs-on: ubuntu-22.04
    container: lskjs/dind
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: api
      - uses: ./.github/actions/docker

  # build_web:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.2.0'
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8.1.0
  #     - run: pnpm install
  #     - run: pnpm build
  #     - run: pnpm -F "." deploy .release